import Link from 'next/link';
import PageHero from '@/components/PageHero';
import FilterBar from '@/components/FilterBar';
const categories = ['Все категории', 'Монолит', 'Фасады', 'Электрика', 'Благоустройство', 'Опиловка', 'Поставка материалов', 'Аренда техники'];
const cards = [
  { badge: 'Срочно', title: 'Фасадные работы на жилом комплексе', text: 'Нужен подрядчик на фасад, утепление и облицовку. Требуется команда с опытом, собственной организацией процессов и выходом на объект в ближайшие десять дней.', meta: 'Турция · от 38 млн ₽ · 4 месяца' },
  { badge: 'Новый', title: 'Благоустройство дворовой территории', text: 'Требуются дорожки, озеленение, освещение, малые формы и работы по ливневой системе. Нужен подрядчик под ключ с техкартой, поставками и понятной сметой.', meta: 'Россия · от 11 млн ₽ · 45 дней' },
  { badge: 'VIP', title: 'Инженерные сети производственного корпуса', text: 'Ищем подрядчика на внутренние сети, вентиляцию, автоматику и пусконаладку. Рассматриваются компании с промышленным опытом и инженерным составом.', meta: 'Казахстан · по договору · 2 этапа' },
  { badge: 'Горящий заказ', title: 'Демонтаж и вывоз строительного мусора', text: 'Необходима бригада с техникой на срочный демонтаж внутренних перегородок, сортировку и вывоз мусора с соблюдением графика и норм объекта.', meta: 'Россия · от 4,2 млн ₽ · 18 дней' },
  { badge: 'Новый', title: 'Поставка инженерных материалов', text: 'Требуется поставщик кабеля, трубы, крепежа и комплектующих для объекта в две очереди. Важно подтвердить сроки, логистику и спецификацию по позициям.', meta: 'Россия · бюджет по заявке · 2 месяца' },
  { badge: 'Срочно', title: 'Аренда спецтехники под монолит', text: 'Нужны автокран, манипулятор и виброоборудование под устройство монолитного каркаса. Желательна подача техники в течение недели и сопровождение операторов.', meta: 'Узбекистан · от 7,8 млн ₽ · 30 дней' }
];
export default function OrdersPage() { return (
  <main className="page"><div className="container">
    <PageHero tag="Заказы / Подряды" title="Заказы и подрядные задачи" text="Размещайте и находите заказы, подряд, субподряд, коммерческие объекты, поставки, аренду техники и работы по благоустройству." visual="orders" actions={<><Link href="/orders/create" className="btn btn-primary">Разместить заказ</Link><Link href="/request?mode=contractor" className="btn btn-secondary">Найти подрядчика</Link></>} />
    <section className="section section-soft"><FilterBar searchPlaceholder="Что ищете?" selects={['Страна', 'Город', 'Категория', 'Бюджет', 'Статус']} /><div className="pill-row">{categories.map((item, idx) => <span key={item} className={`pill ${idx===0?'pill-active':''}`}>{item}</span>)}</div></section>
    <section className="section"><div className="section-header"><div><h2 className="section-title">Актуальные заказы</h2><p className="section-text">Подборка подрядных задач, поставок и объектных этапов, которые требуют отклика, связи и понятной рабочей коммуникации.</p></div></div><div className="actions-grid orders-main-layout"><div className="order-grid orders-main-grid">{cards.map((card) => <article key={card.title} className="order-card card"><span className="badge">{card.badge}</span><h3 className="card-subtitle card-title-compact">{card.title}</h3><p className="card-text">{card.text}</p><div className="meta">{card.meta}</div><div className="card-actions card-actions-bottom"><Link href="/request?mode=contractor" className="btn btn-secondary">Подробнее</Link><Link href="/request?mode=contractor" className="btn btn-primary">Откликнуться</Link></div></article>)}</div><aside className="panel card orders-side-panel"><span className="page-tag">Подборка</span><h3 className="card-subtitle">Быстрый подбор без ручной путаницы</h3><p className="card-text">Найдите подрядчика, оставьте запрос или перейдите к нужному формату работы по объекту без лишних шагов и пустых экранов.</p><div className="side-panel-points"><div>Подрядчики и субподряд</div><div>Поставки и техника</div><div>Запросы по объекту</div></div><Link href="/request" className="btn btn-primary">Оставить заявку</Link></aside></div></section>
  </div></main>
)}
