import Link from 'next/link';
import HeroVisual from '@/components/HeroVisual';

const roles = [
  ['Заказчики', 'Размещают объекты, заказы, подряды, тендеры и запросы на материалы, технику и специалистов. Получают отклики и понятный сценарий сопровождения по объекту.'],
  ['Подрядчики', 'Ищут заказы, объекты, субподряды, материалы и технику для выполнения работ. Видят структуру объекта, сроки, бюджет и способ входа в проект.'],
  ['Специалисты', 'Находят объекты и работодателей, показывают опыт, портфолио и быстро откликаются на предложения по конкретным видам работ.'],
  ['Компании', 'Ведут профиль, получают входящие запросы и ищут подрядчиков, людей и ресурсы. Формируют доверие через описание, кейсы и специализацию.']
];
const categories = ['Монолит', 'Фасады', 'Отделка', 'Электрика', 'Благоустройство', 'Опиловка', 'Вывоз мусора', 'Аренда техники'];
const orders = [
  { badge: 'Срочно', title: 'Фасадные работы на жилом комплексе', text: 'Нужен подрядчик на утепление, облицовку и устройство мокрого фасада. Ищем команду с подтверждённым опытом, понятным графиком мобилизации и готовностью быстро зайти на объект.', meta: 'Турция · от 38 млн ₽ · старт через 10 дней' },
  { badge: 'Новый', title: 'Благоустройство и малые формы', text: 'Требуются дорожки, озеленение, освещение, ливневая система и монтаж малых архитектурных форм. Нужен подрядчик, который закроет весь контур двора и исполнительную документацию.', meta: 'Россия · от 9,5 млн ₽ · 45 дней' },
  { badge: 'VIP', title: 'Инженерные сети производственного корпуса', text: 'Нужен подрядчик на внутренние сети, вентиляцию, автоматику и пусконаладочные работы. Приоритет у команд, которые ведут объект под ключ и умеют держать темп по этапам.', meta: 'Казахстан · по договору · 2 этапа' }
];
export default function HomePage() {
  return (
    <main className="page"><div className="container">
      <section className="hero-grid card"><div className="hero-copy"><span className="hero-tag">Строительная платформа</span><h1 className="hero-title">Единая платформа для заказов, подрядов, специалистов, компаний и документов</h1><p className="hero-text">Помогаем находить исполнителей, размещать заказы, работать с документами и быстрее решать спорные вопросы по проектам. Главный экран стал плотнее, с большим количеством полезного контента и без пустых углов.</p><div className="hero-actions"><Link href="/orders/create" className="btn btn-primary">Разместить заказ</Link><Link href="/documents" className="btn btn-secondary">Документы и споры</Link></div><div className="hero-stats"><div className="hero-stat"><div className="hero-stat-value">1 250+</div><div className="hero-stat-label">готовых документов и шаблонов</div></div><div className="hero-stat"><div className="hero-stat-value">3 800+</div><div className="hero-stat-label">активных пользователей платформы</div></div><div className="hero-stat"><div className="hero-stat-value">750+</div><div className="hero-stat-label">разобранных спорных ситуаций</div></div><div className="hero-stat"><div className="hero-stat-value">200+</div><div className="hero-stat-label">объектов в работе и подборе</div></div></div></div><div className="hero-visual"><HeroVisual variant="hero" /></div></section>
      <section className="section section-soft section-roles"><div className="section-header"><div><h2 className="section-title">Для кого платформа</h2><p className="section-text">Каждая роль получает свой понятный сценарий работы: размещение, поиск, документы, связь и сопровождение объекта. Под карточками теперь больше полезного текста, чтобы блок не выглядел пустым.</p></div></div><div className="role-grid">{roles.map(([title,text])=><div className="role-card card" key={title}><div className="role-accent" /><h3 className="card-subtitle">{title}</h3><p className="card-text card-text-long">{text}</p></div>)}</div></section>
      <section className="section section-soft"><div className="section-header"><div><h2 className="section-title">Категории работ</h2><p className="section-text">Широкий каталог под стройку, подряд, эксплуатацию, материалы, технику и сервисные задачи по объектам. Плашки разнесены свободнее и легче читаются.</p></div></div><div className="pill-row">{categories.map((item,index)=><span className={`pill ${index===0?'pill-active':''}`} key={item}>{item}</span>)}</div></section>
      <section className="section"><div className="section-header section-header-stack-mobile"><div><h2 className="section-title">Заказы / Подряды</h2><p className="section-text">Витрина заказов стала ровнее: карточки плотные, тексты длиннее, мета-строка читается сразу, а кнопки стоят на своей линии и не наезжают друг на друга.</p></div><Link href="/orders" className="btn btn-primary">Все заказы</Link></div><div className="home-orders-layout"><div className="order-grid home-order-grid">{orders.map((order)=><article className="order-card order-card-reworked card" key={order.title}><span className="badge">{order.badge}</span><h3 className="card-subtitle card-title-compact">{order.title}</h3><p className="card-text card-text-long">{order.text}</p><div className="meta meta-strong">{order.meta}</div><div className="card-actions card-actions-equal"><Link href="/orders" className="btn btn-secondary">Подробнее</Link><Link href="/orders/create" className="btn btn-primary">Откликнуться</Link></div></article>)}</div><div className="home-orders-side"><div className="visual-card visual-card-feature card"><HeroVisual variant="handshake" /></div><div className="feature-card card"><span className="page-tag">Быстрый подбор</span><h3 className="card-subtitle">Не хотите искать вручную?</h3><p className="card-text card-text-long">Оставьте заявку, и платформа подберёт подрядчиков, специалистов, поставщиков или документы под ваш объект. Этот блок специально вынесен отдельно, чтобы витрина заказов не ломалась по сетке.</p><div className="card-actions card-actions-equal"><Link href="/request" className="btn btn-primary">Оставить заявку</Link><Link href="/request?mode=contractor" className="btn btn-secondary">Найти подрядчика</Link></div></div></div></div></section>
      <section className="section"><div className="services-duo"><div className="card card-split services-duo-main"><div className="services-duo-copy split-side"><span className="page-tag page-tag-light">Проекты и чертежи</span><h2 className="section-title split-title">Загрузите проект или чертёж и получите наглядную визуализацию</h2><p className="section-text split-text">Рабочие материалы переводятся в понятный визуальный формат для согласования, обсуждения и презентации проекта. Внутри формы разные размеры экранов под разные сценарии: проект, чертёж, документ или поддержка.</p><div className="hero-actions"><Link href="/request?mode=project" className="btn btn-primary">Загрузить проект</Link><Link href="/request?mode=drawing" className="btn btn-secondary">Загрузить чертёж</Link></div></div><div className="visual-card services-duo-visual"><HeroVisual variant="technique" /></div></div><div className="services-duo-side"><div className="feature-card card"><h3 className="card-subtitle">Документы, споры и кейсы</h3><p className="card-text card-text-long">Шаблоны договоров, актов, КС-2, КС-3, претензий и других документов для работы с заказчиком и подрядчиком. Блок усилен и теперь выглядит более деловым, а не как простой список.</p><div className="card-actions card-actions-equal"><Link href="/documents" className="btn btn-secondary">Открыть документы</Link><Link href="/disputes" className="btn btn-primary">Решить спор</Link></div></div><div className="feature-card card"><h3 className="card-subtitle">Сметы и расчёты</h3><p className="card-text card-text-long">Подготовка смет, рабочих расчётов и предварительная оценка рентабельности работ и участия в проекте. Визуальная подача стала плотнее и ближе к деловому сервису.</p><div className="card-actions"><Link href="/documents" className="btn btn-primary btn-full">Рассчитать смету</Link></div></div></div></div></section>
    </div></main>
  );
}
