import Link from "next/link";
import { ReactNode } from "react";
export function SiteHeader({ active }: { active?: string }) {
  const links = [
    { href: "/orders", label: "Заказы / Подряды" },
    { href: "/tenders", label: "Тендеры" },
    { href: "/specialists", label: "Специалисты" },
    { href: "/companies", label: "Компании" },
    { href: "/documents", label: "Документы" },
    { href: "/disputes", label: "Споры" },
  ];
  return <header className="site-header"><div className="container-ui flex items-center justify-between gap-6 py-4"><Link href="/" className="text-2xl font-bold tracking-tight text-slate-950">СтройКонтур</Link><nav className="hidden items-center gap-5 lg:flex">{links.map(item => <Link key={item.href} href={item.href} className={active===item.href?"nav-link-active":"nav-link"}>{item.label}</Link>)}</nav><div className="flex items-center gap-3"><Link href="/login" className="hidden rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-slate-50 sm:inline-flex">Войти</Link><Link href="/register" className="hidden rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white transition hover:bg-slate-800 sm:inline-flex">Регистрация</Link><Link href="/request" className="btn-primary">Оставить заявку</Link></div></div></header>;
}
export function SiteFooter(){return <footer className="mt-16 border-t border-slate-200 bg-white"><div className="container-ui grid gap-10 py-12 md:grid-cols-[1.2fr_1fr_1fr]"><div><div className="text-xl font-bold text-slate-950">СтройКонтур</div><p className="mt-3 max-w-md text-sm leading-7 text-slate-600">Платформа для заказов, подрядов, специалистов, компаний и документов в строительстве.</p></div><div><div className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-500">Разделы</div><div className="mt-4 grid gap-3"><Link href="/orders" className="footer-link">Заказы / Подряды</Link><Link href="/specialists" className="footer-link">Специалисты</Link><Link href="/companies" className="footer-link">Компании</Link><Link href="/documents" className="footer-link">Документы</Link></div></div><div><div className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-500">Служебное</div><div className="mt-4 grid gap-3"><Link href="/request" className="footer-link">Оставить заявку</Link><Link href="/news" className="footer-link">Новости</Link><Link href="/ideas" className="footer-link">Идеи</Link><Link href="/ai-admin" className="footer-link">ИИ-админка</Link></div></div></div></footer>}
export function PageIntro({ eyebrow, title, text, actions }: { eyebrow?: string; title: string; text: string; actions?: ReactNode }) {return <section className="py-10 sm:py-14"><div className="container-ui"><div className="max-w-4xl">{eyebrow ? <div className="pill">{eyebrow}</div> : null}<h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-base leading-8 text-slate-600">{text}</p>{actions ? <div className="mt-8 flex flex-wrap gap-3">{actions}</div> : null}</div></div></section>;}
export function ConstructionArt({ light=false }: { light?: boolean }){return <div className={light?"relative h-full min-h-[260px] overflow-hidden rounded-[28px] bg-slate-100":"relative h-full min-h-[320px] overflow-hidden rounded-[28px] bg-slate-900/60"}><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,0.22),transparent_38%)]" /><div className="absolute left-10 top-12 h-44 w-28 rounded-t-[20px] border-2 border-orange-400/70 bg-orange-400/10" /><div className="absolute left-28 top-24 h-16 w-44 rounded-r-full border-2 border-orange-400/70 bg-transparent" /><div className="absolute left-64 top-38 h-4 w-40 rounded-full bg-orange-400/70" /><div className="absolute right-16 top-14 h-52 w-52 rounded-full border border-white/10 bg-white/5" /><div className="absolute right-24 top-24 h-36 w-36 rounded-full border border-white/10 bg-white/5" /><div className="absolute bottom-10 left-10 right-10 h-1 rounded-full bg-white/10" /></div>}
